namespace Wing
{
    public enum InputMask
    {
        Default,
        UpperCase,
        LowerCase,
        Text,
        Short,
        Integer,
        Number,
        Number_Positive,
        Number_Rounded,
        Number_Rounded_Positive,
        Currency,
        Currency_Positive,
        Percent,
        Percent_Integer,
        Percent_Positive,
        Percent_Rounded,
        Percent_Integer_Positive,
        Percent_Rounded_Positive,
        Date,
        DateTime,
        DateShortTime,
        CPF,
        CNPJ,
        Phone,
        Password,
        CEP,
        Email,
        Custom
    }
}
